#!/bin/bash

if yum list installed httpd &>/dev/null 
then
    echo "httpd installed continuing"
else
	echo "httpd not installed"	
	yum -y install httpd &> /dev/null
fi

VAR=$(hostname -s)
sed -i -e "s/#ServerName www.example.com:80/ServerName $VAR:80/" /etc/httpd/conf/httpd.conf

sed -i -e "s/Options Indexes FollowSymLinks/Options Indexes/g" /etc/httpd/conf/httpd.conf

service httpd start &>/dev/null
if [ "$?" -eq 0 ]
then
	echo "service httpd starts with no errors"
	service httpd stop &>/dev/null
else
	echo "service httpd starts with errors" >&2
	exit 5
fi


if yum list installed php &>/dev/null 
then
    echo "php installed continuing"
	if [ -f "/etc/httpd/conf.d/php.conf" ]
	then
		echo "php.conf exists"
	else
		echo "php.conf doesn't exists" >&2
		exit 4
	fi
else
	echo "php not installed"	
	yum -y install php &>/dev/null
	if [ -f "/etc/httpd/conf.d/php.conf" ]
	then
		echo "php.conf exists"
	else
		echo "php.conf doesn't exists" >&2
		exit 4
	fi

fi


if [ yum list installed mysql-server &>/dev/null ] && [ yum list installed php-mysql &>/dev/null  ] 
then
    echo "mysql-server and php-mysql installed continuing"
else
	echo "mysql-server and php-mysql not installed"	
	yum -y install mysql-server &>/dev/null
	yum -y install php-mysql &>/dev/null
fi

service httpd restart &>/dev/null

chkconfig --add httpd &>/dev/null
chkconfig --add mysqld &>/dev/null
chkconfig httpd on &>/dev/null
chkconfig mysqld on &>/dev/null
chkconfig --list httpd >&1
chkconfig --list mysqld >&1

yum -y install wget &>/dev/null
wget http://boxes.cs.ucr.edu/cs183/mysql.txt &>/dev/null
wget http://boxes.cs.ucr.edu/cs183/gradebook.txt &>/dev/null
mv gradebook.txt gradebook.php
mv gradebook.php /var/www/html/

/etc/init.d/mysqld start &>/dev/null
mysql < mysql.txt &>/dev/null 

#diff <(curl http://boxes.cs.ucr.edu/cs183/gradebook.txt) <(curl http://127.0.0.1/gradebook.php)

wget http://127.0.0.1/gradebook.php &>/dev/null

echo "<h1>183 Gradebook</h1>" >> out.txt
echo "<pre>" >> out.txt
echo "    Claire: 92" >> out.txt
echo "       Bob: 90" >> out.txt
echo "     Alice: 80" >> out.txt
echo "     David: 60" >> out.txt
echo "             " >> out.txt
echo "</pre>" >> out.txt
diff gradebook.php out.txt &>/dev/null
if [ "$?" -eq 0 ]
then
	exit 0
else
	exit 8
fi
